routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes();
Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::group([
    'middleware' => 'authRoleUser'
], function () {
    Route::get('/', [\App\Http\Controllers\Front\BlogController::class, 'index'])->name('index');
    Route::get('/blog/{item}', [\App\Http\Controllers\Front\BlogController::class, 'item'])->name('blog.item');
    Route::match(['get', 'post'],'/profile', [\App\Http\Controllers\Front\ProfileController::class, 'index'])->name('profile');
    Route::get('/profile/delete', [\App\Http\Controllers\Front\ProfileController::class, 'delete'])->name('profile.delete');
});

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => 'authRoleAdmin'
], function () {
    Route::group([
        'as' => 'blog.',
        'prefix' => 'blog',
    ], function () {
        Route::get('/', [App\Http\Controllers\Admin\BlogController::class, 'index'])->name('index');
        Route::match(['get', 'post'], '/form', [App\Http\Controllers\Admin\BlogController::class, 'form'])->name('form');
        Route::match(['get', 'post'], '/form/{id}', [App\Http\Controllers\Admin\BlogController::class, 'form'])->name('id');
        Route::get('/action/{id}/{action}', [App\Http\Controllers\Admin\BlogController::class, 'action'])->name('action');
    });
});

app/Models/BlogItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BlogItem extends Model
{
    protected $fillable = [
        'title',
        'body',
        'image_url'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    const ROLE_USER = 1;
    const ROLE_ADMIN = 2;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'email',
        'password',
        'role_id',
        'avatar',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlogItem;
use App\Services\UnsplashService;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index(Request $request)
    {
        $query = BlogItem::orderBy('id', 'DESC');
        return view('admin.blog.index',
            [
                'pagination' => $query->paginate(4, ['*'], 'page', $request->get('page', 1)),
            ]);
    }

    public function form(Request $request, $id = null)
    {
        $item = null;
        if ($request->isMethod('POST')) {
            $request->validate([
                'title' => 'required|max:255',
                'body' => 'required',
            ]);

            if ($id) {
                $item = BlogItem::find($id);
            }
            if ($item) {
                $image_url = $item->image_url;
                if ($request->get('is_generate_new_photo')) {
                    $unsplash_image = UnsplashService::getImage();
                    $image_url = $unsplash_image->urls['small'];
                }
                $item->update(array_merge($request->only(['title', 'body']), ['image_url' => $image_url]));
            } else {
                $unsplash_image = UnsplashService::getImage();
                $image_url = $unsplash_image->urls['small'];
                $item = BlogItem::create(array_merge($request->only(['title', 'body']), ['image_url' => $image_url]));
                $id = $item->id;
            }
            return redirect(route('admin.blog.id', $id));
        }
        if ($id) {
            $item = BlogItem::find($id);
        }
        return view('admin.blog.form', ['item' => $item]);
    }

    public function action(Request $request, $id, $action)
    {
        $item = BlogItem::find($id);
        if ($item) {
            switch ($action) {
                case 'delete':
                    $item->delete();
                    break;
            }
        }
        return redirect(route('admin.blog.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Front/BlogController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Http\Resources\BlogItemResource;
use App\Models\BlogItem;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index(Request $request)
    {
        $query = BlogItem::orderBy('id', 'DESC');
        $items = BlogItemResource::collection($query->paginate(4, ["*"], "page", $request->get('page')));
        return view('front.blog.index', [
            'pagination' => $items
        ]);
    }

    public function item(BlogItem $item)
    {
        return view('front.blog.item', [
            'item' => $item
        ]);
    }
}

app/Http/Controllers/Front/ProfileController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class ProfileController extends Controller
{

    public function index(Request $request)
    {
        if ($request->isMethod('POST')) {
            $id = Auth::id();
            $request->validate([
                'email' => "required|max:255|email|unique:users,email,$id",
            ]);
            $user = Auth::user();
            $update_data = [
                'email' => $request->get('email')
            ];
            if ($request->get('password')) {
                $update_data['password'] = Hash::make($request->get('password'));
            }
            if ($file = $request->file('avatar')) {
                if (strpos($file->getMimeType(), 'image/') !== false
                    && in_array($file->getMimeType(),
                        ['image/jpg', 'image/jpeg', 'image/png']) !== false
                ) {
                    $format = str_replace('image/', '', $file->getMimeType());
                    $photo_name = md5(rand(10000000, 99999999) . time());
                    $full_name = $photo_name . '.' . $format;
                    Storage::disk('public')->put("avatar/$full_name", File::get($file));
                    $update_data['avatar'] = '/storage/avatar/' . $full_name;
                }
            }
            $user->update($update_data);
            return redirect(route('profile'));
        }
        return view('front.profile');
    }

    public function delete()
    {
        $user = Auth::user();
        $user->delete();
        Auth::logout();
        return redirect(route('index'));
    }
}

resources/views/admin/blog/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="post">
            <div class="@error('title') was-validated @enderror">
                <label for="title" class="form-label">Название</label>
                <div class="input-group has-validation">
                    <input type="text" class="form-control" id="title" name="title" placeholder="Название" required
                           value="{{old('title')?old('title'):(!empty($item)?$item->title:'')}}">
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
            <hr class="my-3">
            <div class="@error('body') was-validated @enderror">
                <div class="form-floating">
                        <textarea class="form-control" placeholder="Содержимое блога" id="body" name="body"
                                  style="height: 100px"
                                  required>{{old('body')?old('body'):(!empty($item)?$item->body:'')}}</textarea>
                    <label for="body">Содержимое блога</label>
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
            @if(!empty($item))
                <hr class="my-4">
                <img src="{{$item->image_url}}"/>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="is_generate_new_photo"
                           name="is_generate_new_photo">
                    <label class="form-check-label" for="is_generate_new_photo">Заменить фото</label>
                </div>
            @endif
            <hr class="my-4">
            <button class="w-100 btn btn-primary btn-lg" type="submit">@if(!empty($item))
                    Редактировать
                @else
                    Создать
                @endif</button>
        </form>
    </div>
@endsection

resources/views/admin/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="d-flex gap-2 justify-content-center pb-3">
            <a href="{{route('admin.blog.form')}}" class="btn btn-success rounded-pill px-3" type="button">Создать</a>
        </div>
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">Действие</th>
                </tr>
                </thead>
                <tbody>
                @foreach($pagination->items() as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->title}}</td>
                        <td>
                            <div class="d-flex gap-2">
                                <a href="{{route('admin.blog.id',$item->id)}}" class="btn btn-primary rounded-pill px-3" type="button">Редактировать
                                </a>
                                <a href="{{route('admin.blog.action',[$item->id,'delete'])}}" class="btn btn-danger rounded-pill px-3 _confirm_alert" type="button">Удалить</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @include('partials.pagination.index')
        </div>
    </div>
@endsection

resources/views/front/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @foreach($pagination->items() as $item)
                <div class="col-md-6">
                    <div
                        class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <h3 class="mb-0">{{$item->title}}</h3>
                            <div class="mb-1 text-body-secondary">{{$item->created_at}}</div>
                            <p class="card-text mb-auto">{{substr($item->body,0,100)}}...</p>
                            <a href="{{route('blog.item',$item->id)}}"
                               class="icon-link gap-1 icon-link-hover stretched-link">
                                Читать полностью
                                <svg class="bi">
                                    <use xlink:href="#chevron-right"></use>
                                </svg>
                            </a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img class="bd-placeholder-img" style="width: 200px; height: 200px; object-fit: cover;"
                                 src="{{$item->image_url}}"/>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        @include('partials.pagination.index')
    </div>
@endsection

resources/views/front/blog/item.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div
            class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h3 class="mb-0">{{$item->title}}</h3>
                <div class="mb-1 text-body-secondary">{{$item->created_at}}</div>
                <p class="card-text mb-auto">{{substr($item->body,0,100)}}...</p>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img class="bd-placeholder-img" style="width: 200px; height: 200px; object-fit: cover;"
                     src="{{$item->image_url}}"/>
            </div>
        </div>
    </div>
@endsection

resources/views/front/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div>
                <label for="email" class="form-label">Email</label>
                <div class="input-group has-validation">
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email" required
                           value="{{old('email')?old('email'):Auth::user()->email}}">
                    <div class="invalid-feedback @if($errors->first('email')) d-block @endif">
                        {{$errors->first('email')}}
                    </div>
                </div>
            </div>
            <hr class="my-3">
            <div>
                <label for="password" class="form-label">Пароль</label>
                <div class="input-group has-validation">
                    <input type="password" class="form-control" id="password" name="password" placeholder="password">
                </div>
            </div>
            <hr class="my-3">
            <div>
                <label for="formFile" class="form-label">Выбрать аватар (png, jpg, jpeg)</label>
                <input class="form-control" type="file" id="formFile" name="avatar" accept="image/*">
            </div>
            <hr class="my-4">
            <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
        </form>
        <hr class="my-4">
        <a href="{{route('profile.delete')}}" class="w-100 btn btn-danger btn-lg" type="submit">Удалить аккаунт</a>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Тестовое задание</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            @if(Auth::user() && Auth::user()->role_id == \App\Models\User::ROLE_ADMIN)
                <a class="navbar-brand" href="{{ route('admin.blog.index') }}">
                    Блог
                </a>
            @else
                <a class="navbar-brand" href="{{ route('index') }}">
                    Блог
                </a>
            @endif
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav me-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">Авторизация</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->email }}
                                <img src="{{Auth::user()->avatar}}" alt="mdo" width="32" height="32"
                                     class="rounded-circle">
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->role_id == \App\Models\User::ROLE_USER)
                                    <a class="dropdown-item" href="{{ route('profile') }}">
                                        Профиль
                                    </a>
                                @endif
                                <a class="dropdown-item" href="{{ route('logout') }}">
                                    Выйти
                                </a>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/partials/pagination/index.blade.php
@php
    $query_search = '';
    $count = 0;
    foreach (!empty($filters)?$filters:[] as $id => $value) {
        $query_search .= '&'.$id . '=' . $value;
        $count++;
    }
@endphp
@if($pagination->currentPage() > 1 || $pagination->hasMorePages())
    <nav aria-label="Page navigation example" style="margin: 0 auto;">
        <ul class="pagination" style="justify-content: center;">
            @if($pagination->currentPage() > 2)
                <li class="page-item">
                    <a class="page-link" href="{{route(Route::current()->getName())}}?page=1" aria-label="1">
                        <span aria-hidden="true">1</span>
                    </a>
                </li>
            @endif
            @if($pagination->currentPage() == 1)
                @include('partials.pagination.page_first')
            @elseif(!$pagination->hasMorePages())
                @include('partials.pagination.page_current')
            @else
                @include('partials.pagination.page_last')
            @endif

            @if($pagination->hasMorePages() && $pagination->lastPage() !== ($pagination->currentPage() + 1))
                <li class="page-item">
                    <a class="page-link"
                       href="{{route(Route::current()->getName())}}?page={{$pagination->lastPage()}}{{$query_search}}"
                       aria-label="Next">
                        <span aria-hidden="true">{{$pagination->lastPage()}}</span>
                    </a>
                </li>
            @endif
        </ul>
    </nav>
@endif

resources/views/partials/pagination/page_current.blade.php
@if($pagination->lastPage() > 3)
    <li class="page-item">
        <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() - 2}}{{$query_search}}">{{$pagination->currentPage() - 2}}</a>
    </li>
@endif
<li class="page-item">
    <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() - 1}}{{$query_search}}">{{$pagination->currentPage() - 1}}</a>
</li>
<li class="page-item active">
    <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage()}}{{$query_search}}">{{$pagination->currentPage()}}</a>
</li>

resources/views/partials/pagination/page_first.blade.php
<li class="page-item active">
    <a class="page-link" href="{{route(Route::current()->getName())}}?page=1{{$query_search}}">1</a></li>
@if($pagination->lastPage() >=2)
    <li class="page-item"><a class="page-link" href="{{route(Route::current()->getName())}}?page=2{{$query_search}}">2</a>
    </li>
@endif
@if($pagination->lastPage() >3)
    <li class="page-item"><a class="page-link" href="{{route(Route::current()->getName())}}?page=3{{$query_search}}">3</a>
    </li>
@endif

resources/views/partials/pagination/page_last.blade.php
@if($pagination->lastPage() >= $pagination->currentPage() - 1)
    <li class="page-item">
        <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() - 1}}{{$query_search}}">{{$pagination->currentPage() - 1}}</a>
    </li>
@endif
@if($pagination->lastPage() >=2)
    <li class="page-item active">
        <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage()}}{{$query_search}}">{{$pagination->currentPage()}}</a>
    </li>
@endif
@if($pagination->lastPage() >= $pagination->currentPage() + 1)
    <li class="page-item">
        <a class="page-link" href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() + 1}}{{$query_search}}">{{$pagination->currentPage() + 1}}</a>
    </li>
@endif